### ISSUE TITLE
subsequence and label related query

### ISSUE THREAD

**Issue by nsankar** [Jokonu/abimca#2]
@Jokonu  Thanks for developing this interesting clustering technique and library

I have the following queries:

In your example code for labels shown below (a) what are the typical values of labels ? does it also contain labels to indicate noise _(i.e outlier points that are not a part of any cluster.. )_? (b) does each label indicate a specific subsequence?

```
   Compute offline clustering
    labels = si.predict(X)
```

Thanks in advance.

**Comment by Jokonu** [comment]
Hi @nsankar,

Thanks for taking interest in the algorithm.

Regarding your questions:

(a) typical values are natural numbers, where the zero stands for outliers or undefined subsequence.
Example:
```
>>> labels
[0, 0, 1, 1, 1, 0, 0, 2, 2, 2]
```

(b) Yes, each natural number greater than zero is indicating the belonging of a datapoint to this specific subsequence.

You can also look at my [preprint](https://arxiv.org/abs/2209.04213) for details.
I hope this helps.

**Comment by nsankar** [comment]
@Jokonu  Got it. Thank you for the inputs.

**Comment by nsankar** [comment]
@Jokonu Another related question. Suppose I have a time-series data (multi variate features). After building a ABIMCA model , lets say ABIMCA model flags a new test data point vector like V = [x1,x2,x3,x4] as an anomaly (label =0). 

My question is we know that a predicted data V is labeled as abnormal. But, how do we determine which feature (e.g. X1 or X2..) in the data point is causing it to be an outlier? What is your advice to determine this?
